#!/usr/bin/env node
/*
 * generate-tokens.mjs — Figma変数(get_variable_defs)からCSS/TSトークンを生成
 *
 * 使い方:
 *   node generate-tokens.mjs <variables.json> <出力dir>
 *
 * 入力: get_variable_defs の union 結果を想定した JSON。例:
 *   {
 *     "text/primary": "#111111",
 *     "space/12": "12px",
 *     "radius.md": 8,
 *     "label/xs-bold": { "fontFamily": "Noto Sans JP", "fontSize": 12, "letterSpacing": 4 }
 *   }
 *   値が string / number / object のケースを柔軟にパースする。
 *   object 値はフラット化して展開できるもの（string/number リーフ）だけ採用し、
 *   それ以外（配列・null 等）は skipped として報告する。
 *
 * 出力（<出力dir> に2ファイル）:
 *   tokens.css : :root { --text-primary: #111111; ... }
 *                名前変換は「/」と「.」→「-」（空白も「-」に正規化）
 *   tokens.ts  : export const tokens = { "--text-primary": "#111111", ... } as const;
 *                tokens.css の完全ミラー ＋ letter-spacing系のem換算ヘルパ付き
 *
 * 単位の扱い:
 *   - letterSpacing の数値リーフは Figma の整数%とみなし em に自動換算して出力する
 *     （例: letterSpacing 4 → "0.04em"。SKILL.md 工程①「em換算」の実装。css/ts 両方に換算後の値が入る）
 *   - それ以外の単位なし数値（radius: 8 等）はそのまま出力し warn を出す。
 *     CSSで単位が必要なトークンは入力JSON側で "8px" のような単位付き文字列にする
 */
import fs from "node:fs";
import path from "node:path";

const [, , inFile, outDir] = process.argv;
if (!inFile || !outDir) {
  console.error("usage: node generate-tokens.mjs <variables.json> <出力dir>");
  process.exit(1);
}

let raw;
try {
  raw = JSON.parse(fs.readFileSync(inFile, "utf8"));
} catch (e) {
  console.error(`error: 入力JSONを読めません: ${inFile}\n${e.message}`);
  process.exit(1);
}
if (raw === null || typeof raw !== "object" || Array.isArray(raw)) {
  console.error("error: 入力はトップレベルがオブジェクトのJSONである必要があります");
  process.exit(1);
}

// ---- フラット化（object値は string/number リーフだけ展開、他は skipped） ----
const flat = new Map(); // 元キー(フラット化後) -> 値
const skipped = [];
function put(key, val) {
  if (typeof val === "string" || typeof val === "number") {
    flat.set(key, val);
    return;
  }
  if (val !== null && typeof val === "object" && !Array.isArray(val)) {
    for (const [k, v] of Object.entries(val)) put(`${key}/${k}`, v);
    return;
  }
  skipped.push({ key, reason: `unsupported value type: ${Array.isArray(val) ? "array" : typeof val}` });
}
for (const [k, v] of Object.entries(raw)) put(k, v);

// ---- letter-spacing の em 換算（Figmaの整数letter-spacing=% → em。SKILL.md 工程①） ----
// css/ts の生成前に flat の値ごと換算するので、tokens.ts は換算後の完全ミラーのまま。
const unitlessKeys = [];
for (const [key, value] of flat) {
  if (typeof value !== "number") continue;
  // リーフ名でもグループ名でも判定（"label/xs-bold/letterSpacing" と "letter-spacing/wide" の両対応）
  if (key.split(/[\/.]/).some((seg) => /^letter-?spacing$/i.test(seg))) {
    flat.set(key, `${value / 100}em`); // 例: 4 → 0.04em
  } else {
    unitlessKeys.push(key);
  }
}
if (unitlessKeys.length) {
  console.warn(
    `warn: 単位なし数値トークン ${unitlessKeys.length}件（CSSで単位が必要なら入力JSON側で "8px" 等の単位付き文字列にする）: ${unitlessKeys.join(", ")}`
  );
}

// ---- 名前変換: / と . → - （空白も - に、連続 - は圧縮） ----
const toVarName = (key) =>
  "--" +
  key
    .replace(/[\/.]/g, "-")
    .replace(/\s+/g, "-")
    .replace(/-{2,}/g, "-")
    .replace(/^-+|-+$/g, "");

const cssVars = new Map(); // varName -> {value, sourceKey}
for (const [key, value] of flat) {
  const name = toVarName(key);
  if (cssVars.has(name) && cssVars.get(name).sourceKey !== key) {
    console.warn(
      `warn: 変数名が衝突: "${key}" と "${cssVars.get(name).sourceKey}" が両方 ${name} になる（後勝ち）`
    );
  }
  cssVars.set(name, { value, sourceKey: key });
}

// ---- tokens.css ----
const cssLines = [];
cssLines.push("/* AUTO-GENERATED by generate-tokens.mjs — 手編集しない */");
cssLines.push(`/* source: ${path.basename(inFile)} */`);
cssLines.push(":root {");
for (const [name, { value, sourceKey }] of cssVars) {
  cssLines.push(`  ${name}: ${value}; /* ${sourceKey} */`);
}
cssLines.push("}");
cssLines.push("");
const cssOut = cssLines.join("\n");

// ---- tokens.ts（tokens.css の完全ミラー） ----
const tsLines = [];
tsLines.push("// AUTO-GENERATED by generate-tokens.mjs — 手編集しない");
tsLines.push(`// source: ${path.basename(inFile)}`);
tsLines.push("// tokens.css の :root カスタムプロパティの完全ミラー");
tsLines.push("export const tokens = {");
for (const [name, { value, sourceKey }] of cssVars) {
  tsLines.push(`  ${JSON.stringify(name)}: ${JSON.stringify(value)}, // ${sourceKey}`);
}
tsLines.push("} as const;");
tsLines.push("");
tsLines.push("export type TokenName = keyof typeof tokens;");
tsLines.push("");
tsLines.push("/*");
tsLines.push(" * letter-spacing 系トークンの em 換算ヘルパ");
tsLines.push(" * Figma の letterSpacing は整数=%（fontSize に対する割合）で入っていることが多い。");
tsLines.push(" * CSS の letter-spacing は 1em = fontSize なので、%値 / 100 がそのまま em 値になる。");
tsLines.push(" *   例: letterSpacing 4(%) → 0.04em");
tsLines.push(" * px が欲しい場合は fontSize × n / 100 で計算する。");
tsLines.push(" */");
tsLines.push("export function letterSpacingPercentToEm(percent: number): string {");
tsLines.push("  return `${percent / 100}em`;");
tsLines.push("}");
tsLines.push("");
tsLines.push("export function letterSpacingPercentToPx(percent: number, fontSizePx: number): number {");
tsLines.push("  return (fontSizePx * percent) / 100;");
tsLines.push("}");
tsLines.push("");
const tsOut = tsLines.join("\n");

// ---- 書き出し ----
fs.mkdirSync(outDir, { recursive: true });
const cssPath = path.join(outDir, "tokens.css");
const tsPath = path.join(outDir, "tokens.ts");
fs.writeFileSync(cssPath, cssOut, "utf8");
fs.writeFileSync(tsPath, tsOut, "utf8");

console.log(`wrote: ${cssPath} (${cssVars.size} tokens)`);
console.log(`wrote: ${tsPath} (${cssVars.size} tokens + helpers)`);
if (skipped.length) {
  console.log(`skipped (${skipped.length}):`);
  for (const s of skipped) console.log(`  - ${s.key}: ${s.reason}`);
}
